version: '3'
services:

  db-cats-api:
    image: postgres:12
    restart: always
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: admin
      POSTGRES_DB: cats-api
    ports:
      - 5444:5432


